# Tensors

In [1]:
import torch
torch.empty(5, 3)

tensor([[1.2612e-44, -0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1704e-41, 0.0000e+00]])

In [2]:
torch.rand(5,3)

tensor([[0.2033, 0.9108, 0.5976],
        [0.3178, 0.8671, 0.6511],
        [0.5186, 0.3667, 0.8964],
        [0.9629, 0.8099, 0.4411],
        [0.5968, 0.8171, 0.8007]])

In [3]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [5]:
x = torch.tensor([5.5, 3])
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0728,  0.0167, -1.6277],
        [-1.7127,  0.7603,  1.7005],
        [ 0.9695,  1.0495, -0.3014],
        [-0.1805, -0.5493, -1.4254],
        [-0.3851, -1.3400,  1.1574]])


In [6]:
x.size()

torch.Size([5, 3])

# Operations

In [7]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)

print(x + y)
print(torch.add(x,y))

result = torch.empty(2, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)

tensor([[0.8571, 0.9356, 0.7336],
        [1.7075, 1.6327, 0.5394]])
tensor([[0.8571, 0.9356, 0.7336],
        [1.7075, 1.6327, 0.5394]])
tensor([[0.8571, 0.9356, 0.7336],
        [1.7075, 1.6327, 0.5394]])
tensor([[0.8571, 0.9356, 0.7336],
        [1.7075, 1.6327, 0.5394]])


In [8]:
print(x[:, 1])

tensor([0.7219, 0.8980])


In [9]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8606])
0.8606249690055847


# NumPy Bridge

The Torch Tensor and NumPy array will **share their underlying memory locations** (if the Torch Tensor is on CPU), and changing one will change the other.

## Converting a Torch Tensor to a NumPy Array

In [11]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [12]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [14]:
torch.cuda.is_available()

False